# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

# DataSource settings: set here your own configurations for the database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challengescoresmicroservice?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&useSSL=false
    username: root
    password: root
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jooq:
    sql-dialect: Mysql
