# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_template?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
  jackson:
    mapper:
      use-getters-as-setters: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: shanoir-ng-rabbitmq
  session:
    store-type: none
front.server.url: http://shanoir-ng-nginx
#keycloak
keycloak:
  cors: true
  realm: shanoir-ng
  auth-server-url: http://localhost/auth
  ssl-required: external
  resource: shanoir-ng-templates
  securityConstraints:
    - authRoles: 
      - ROLE_ADMIN
      - ROLE_EXPERT
      - ROLE_GUEST
      - ROLE_USER
    - securityCollections:
      - name: spring secured api
      - patterns:
        - /*
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-template.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_template?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: localhost
server:
    port: 9902
front.server.url: http://localhost:8080
#keycloak
keycloak:
  auth-server-url: http://localhost/auth
  credentials:
    secret: 3b130530-4e0f-4101-bf56-1a92df705318
# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-template.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_TEMPLATE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    data: classpath:/scripts/test-data-h2.sql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: qualif,prod
  datasource:
    initialize: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
  rabbitmq:
    host: shanoir-ng-rabbitmq
#keycloak
keycloak:
  auth-server-url: SHANOIR_SERVER_URL/auth
